# this is a sample config file for the custom settings
# it's an example that will also be used in case there is no
# custom settings file in the app, as an option to demonstrate or test
# the app's ability to load and change the current settings
["org.gnome.desktop.interface"]
clock-format = '24h'
clock-show-seconds = 'true'
clock-show-weekday = 'true'
gtk-timeout-repeat = 30

["org.gnome.desktop.media-handling"]
automount = 'false'
automount-open = 'false'
autorun-never = 'true'

["org.gnome.desktop.wm.preferences"]
audible-bell = 'false'
button-layout = 'appmenu:minimize,close'
num-workspaces = 3
