["org.gnome.Console"]
audible-bell = 'false' 
custom-font = 'Source Code Pro 13' 
scrollback-lines = 100000 # added a zero
theme = 'night' 
use-system-font = 'false' 

["org.gnome.TextEditor"]
custom-font = 'Source Code Pro Medium 14'
restore-session = 'false'
tab-width = 4
use-system-font = 'false'
wrap-text = 'true'

["org.gnome.World.Secrets"]
generator-use-lowercase = 'true'
generator-use-numbers = 'true'
generator-use-symbols = 'true'
generator-use-uppercase = 'true'

["org.gnome.calculator"]
accuracy = 6
button-mode = 'advanced'

["org.gnome.desktop.interface"]
clock-format = '24h'
clock-show-seconds = 'true'
clock-show-weekday = 'true'
gtk-timeout-repeat = 30

["org.gnome.desktop.media-handling"]
automount = 'false'
automount-open = 'false'
autorun-never = 'true'

["org.gnome.desktop.privacy"]
report-technical-problems = 'true'
send-software-usage-stats = 'true'

["org.gnome.desktop.wm.preferences"]
audible-bell = 'false'
button-layout = 'appmenu:minimize,close'
num-workspaces = 3

["org.gnome.nautilus.list-view"]
default-visible-columns = ['name', 'size', 'date_created', 'date_modified']
default-zoom-level = 'small'
