["org.gnome.Console"]
audible-bell = 'false'
theme = 'night'

["org.gnome.World.Secrets"]
generator-use-lowercase = 'true'
generator-use-numbers = 'true'
generator-use-symbols = 'true'
generator-use-uppercase = 'true'

["org.gnome.calculator"]
accuracy = 6
button-mode = 'advanced'

["org.gnome.desktop.interface"]
clock-format = '24h'
clock-show-seconds = 'true'
clock-show-weekday = 'true'
